title:  "Cassandra.Cardiff.Yoga"
tagline: "yoga is for everyone. Come practice with me."

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Videos', folder: 'pages', file: 'videos.html'}
- {name: 'Testimonials', folder: 'pages', file: 'testimonials.html'}
- {name: 'My Classes', folder: 'pages', file: 'classes.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

#- {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
#- {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
# - {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/casscardiff'}
- {icon: 'facebook', link: 'https://www.facebook.com/cassandra.cardiff'}
- {icon: 'instagram', link: 'https://instagram.com/cascardiff'}
- {icon: 'envelope', link: 'mailto:ccardiff@dal.ca'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}
